// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SendIO.Persistence.Context;

#nullable disable

namespace SendIO.Persistence.Migrations
{
    [DbContext(typeof(SendIOContext))]
    partial class SendIOContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SendIO.Domain.Entities.FileContent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<Guid>("FileHeadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("generatedname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("originalname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("size")
                        .HasColumnType("bigint");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FileHeadId");

                    b.ToTable("filecontent", "dbo");
                });

            modelBuilder.Entity("SendIO.Domain.Entities.FileHead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2");

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("enddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("filehead", "dbo");
                });

            modelBuilder.Entity("SendIO.Domain.Entities.FileContent", b =>
                {
                    b.HasOne("SendIO.Domain.Entities.FileHead", "fileHead")
                        .WithMany("FileContents")
                        .HasForeignKey("FileHeadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("fileHead");
                });

            modelBuilder.Entity("SendIO.Domain.Entities.FileHead", b =>
                {
                    b.Navigation("FileContents");
                });
#pragma warning restore 612, 618
        }
    }
}
